##**POS tagging**

In [1]:
# pos tagging means parts of speech tagging.
# It is NLP tr=echinique where each word in a
# sentence is assigned its grammatical role such as:

# Noun
# Verb
# Adjective
# Pronoun
# Preprosition
# Conjuction

In [2]:
# WHY IS POS TAGGING IMPORTANT?

# POS Taggingis used in:
#  Text Classification
#ChatBocats
# Machine Translation
# Nmaed Entity Recognisation
# Setiment Analysis
# $ Speech Recognisation
# Grammer checking

## **Commmon POS Tagging**

In [12]:
# |POS Tagging    |  Meaning       |
# |---------------|--------------- |
# |NN             | Noun           |
# |NNS            | Plural Noun    |
# |NNP            | Proper Noun    |
# |VB             | Verb           |
# |VBG            | Verb Gerund    |
# |VBD            | Verb Past Tense|
# |JJ             | Adjective      |
# |RB             | Adverb         |
# |PRP            | Pronoun        |
# |IN             | Adjective      |

In [3]:
#  Working Process of POS Tagging ::::

# 1. Sentence is divided into tokens.
# 2. NLP model checks grammar/context
# 3. Appropriate POS tag is assigned to each word.

In [4]:
!pip install spacy
!python -m spacy download en_core_web_sm

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.24.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.4.22)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.23.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.6.0)
Requirement already satisfied: httpx>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.1.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 70.4 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [7]:
import spacy

# Load English model
nlp=spacy.load("en_core_web_sm")

#  Input text
doc=nlp("Harshita is learning NLP.")

# POS tagging
for token in doc:
  print(token.text," -----> ",token.pos_)

Harshita  ----->  PROPN
is  ----->  AUX
learning  ----->  VERB
NLP  ----->  PROPN
.  ----->  PUNCT

In [9]:
#  Example-2

In [10]:
nlp=spacy.load("en_core_web_sm")

text="Harshita plays cricket!!"
doc=nlp(text)
for token in doc:
  print(token.text," ====> ",token.pos_)

Harshita  ====>  PROPN
plays  ====>  VERB
cricket  ====>  NOUN
!  ====>  PUNCT
!  ====>  PUNCT

In [11]:
# Example-3

In [13]:
import spacy
nlp=spacy.load("en_core_web_sm")
text="Harshita is learning NLP."
doc=nlp(text)

for token in doc:
  print(
      " Word: ",token.text,
      " POS: ",token.pos_,
      " TAG: ",token.tag_
      )

 Word:  Harshita  POS:  PROPN  TAG:  NNP
 Word:  is  POS:  AUX  TAG:  VBZ
 Word:  learning  POS:  VERB  TAG:  VBG
 Word:  NLP  POS:  PROPN  TAG:  NNP
 Word:  .  POS:  PUNCT  TAG:  .

In [14]:
# Visulising POS Tagging

In [17]:
import spacy
from spacy import displacy

nlp=spacy.load("en_core_web_sm")
text="Harshita is learning NLP ."

doc=nlp(text)
displacy.serve(doc,style="dep")

Using the 'dep' visualizer
Serving on http://0.0.0.0:5000 ...

Shutting down server on port 5000.

In [ ]:
# IMDB Dataset ---> clean ---> 1 row --->paragraph ---> POS tagging ,NER extract(visulaise)

In [18]:
import pandas as pd
import numpy as np

In [20]:
import pandas as pd

df = pd.read_csv(
    "/content/IMDB Dataset - IMDB Dataset.csv",
    engine='python'
)

df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [21]:
# Clean

In [22]:
df['review']=df['review'].str.lower()

In [23]:
# Remove html Tags

In [24]:
import re

In [25]:
def remove_html_tags(text):
  pattern=re.compile('<.*?>')
  return pattern.sub(r'',text)
df['review']=df['review'].apply(remove_html_tags)
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [26]:
# remove URL

In [28]:
def remove_url(text):
  pattern=re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'',text)

df['review']=df['review'].apply(remove_url)

In [29]:
# Remove punctuation

In [31]:
import string
print(string.punctuation)

exclude=string.punctuation

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [32]:
def remove_punct(text):
  for char in exclude:
    text=text.replace(char,"")
  return text
df['review']=df['review'].apply(remove_punct)
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [33]:
# Spelling correction

In [35]:
from textblob import TextBlob

text = df['review'][0]

blob = TextBlob(text)

print(blob.correct())

one of the other reviews has mentioned that after watching just 1 oz episode you be hooked they are right as this is exactly what happened with metre first thing that struck me about oz was its brutally and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punched with regards to drugs sex or violence its is hardware in the classic use of the words is called oz as that is the nickname given to the onward maximum security state penitentiary it focused mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to manyaryans muslin gangstas nations christians italians irish and more snuffles death stares podgy dealings and shady agreements are never far away would say the main appeal of the show is due to the fact that it goes where other shows wouldn dare forget pretty pictures painted for mainstream audiences forget charm forget romance doesn mess around the first episode i ever saw struck me as so nasty it was surrey i couldn say i was ready for it but as i watched more i developed a taste for oz and got accustomed to the high levels of graphics violence not just violence but injustice crooked guards whole be sold out for a nickel inmates whole kill on order and get away with it well manner middle class inmates being turned into prison birches due to their lack of street skill or prison experience watching oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side

In [36]:
blob

TextBlob("one of the other reviewers has mentioned that after watching just 1 oz episode youll be hooked they are right as this is exactly what happened with methe first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the wordit is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to manyaryans muslims gangstas latinos christians italians irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awayi would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare forget pretty pictures painted for mainstream audiences forget charm forget romanceoz doesnt mess around the first episode i ever saw struck me as so nasty it was surreal i couldnt say i was ready for it but as i watched more i developed a taste for oz and got accustomed to the high levels of graphic violence not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience watching oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side")

In [37]:
import re
import string

text = df['review'][0]

# lowercase
text = text.lower()

# remove html tags
text = re.sub(r'<.*?>', '', text)

# remove punctuation
text = text.translate(str.maketrans('', '', string.punctuation))

# remove numbers
text = re.sub(r'\d+', '', text)

# remove extra spaces
text = re.sub(r'\s+', ' ', text).strip()

print(text)

one of the other reviewers has mentioned that after watching just oz episode youll be hooked they are right as this is exactly what happened with methe first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the wordit is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to manyaryans muslims gangstas latinos christians italians irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awayi would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare forget pretty pictures painted for mainstream audiences forget charm forget romanceoz doesnt mess around the first episode i ever saw struck me as so nasty it was surreal i couldnt say i was ready for it but as i watched more i developed a taste for oz and got accustomed to the high levels of graphic violence not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience watching oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side

In [38]:
text

'one of the other reviewers has mentioned that after watching just oz episode youll be hooked they are right as this is exactly what happened with methe first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the wordit is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to manyaryans muslims gangstas latinos christians italians irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awayi would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare forget pretty pictures painted for mainstream audiences forget charm forget romanceoz doesnt mess around the first episode i ever saw struck me as so nasty it was surreal i couldnt say i was ready for it but as i watched more i developed a taste for oz and got accustomed to the high levels of graphic violence not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience watching oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side'

In [40]:
import spacy
nlp=spacy.load("en_core_web_sm")

doc=nlp(text)
for ent in doc.ents:
  print(ent.text,ent.label_)

one CARDINAL
first ORDINAL
manyaryans muslims NORP
christians NORP
italians NORP
irish NORP
first ORDINAL

In [41]:
from spacy import displacy

import spacy
nlp=spacy.load("en_core_web_sm")

doc=nlp(text)
displacy.render(doc, style="ent", jupyter=True)

In [42]:
nlp=spacy.load("en_core_web_sm")

doc=nlp(text)
for token in doc:
  print(token.text," ====> ",token.pos_)

one  ====>  NUM
of  ====>  ADP
the  ====>  DET
other  ====>  ADJ
reviewers  ====>  NOUN
has  ====>  AUX
mentioned  ====>  VERB
that  ====>  SCONJ
after  ====>  ADP
watching  ====>  VERB
just  ====>  ADV
oz  ====>  ADP
episode  ====>  NOUN
you  ====>  PRON
ll  ====>  AUX
be  ====>  AUX
hooked  ====>  VERB
they  ====>  PRON
are  ====>  AUX
right  ====>  ADJ
as  ====>  SCONJ
this  ====>  PRON
is  ====>  AUX
exactly  ====>  ADV
what  ====>  PRON
happened  ====>  VERB
with  ====>  ADP
methe  ====>  DET
first  ====>  ADJ
thing  ====>  NOUN
that  ====>  PRON
struck  ====>  VERB
me  ====>  PRON
about  ====>  ADP
oz  ====>  PROPN
was  ====>  AUX
its  ====>  PRON
brutality  ====>  NOUN
and  ====>  CCONJ
unflinching  ====>  VERB
scenes  ====>  NOUN
of  ====>  ADP
violence  ====>  NOUN
which  ====>  PRON
set  ====>  VERB
in  ====>  ADP
right  ====>  NOUN
from  ====>  ADP
the  ====>  DET
word  ====>  NOUN
go  ====>  VERB
trust  ====>  VERB
me  ====>  PRON
this  ====>  PRON
is  ====>  AUX
not  ====>  PART
a  ====>  DET
show  ====>  NOUN
for  ====>  ADP
the  ====>  DET
faint  ====>  ADJ
hearted  ====>  ADJ
or  ====>  CCONJ
timid  ====>  ADJ
this  ====>  DET
show  ====>  NOUN
pulls  ====>  VERB
no  ====>  DET
punches  ====>  NOUN
with  ====>  ADP
regards  ====>  NOUN
to  ====>  ADP
drugs  ====>  NOUN
sex  ====>  NOUN
or  ====>  CCONJ
violence  ====>  NOUN
its  ====>  PRON
is  ====>  AUX
hardcore  ====>  NOUN
in  ====>  ADP
the  ====>  DET
classic  ====>  ADJ
use  ====>  NOUN
of  ====>  ADP
the  ====>  DET
wordit  ====>  NOUN
is  ====>  AUX
called  ====>  VERB
oz  ====>  ADP
as  ====>  SCONJ
that  ====>  PRON
is  ====>  AUX
the  ====>  DET
nickname  ====>  NOUN
given  ====>  VERB
to  ====>  ADP
the  ====>  DET
oswald  ====>  ADJ
maximum  ====>  ADJ
security  ====>  NOUN
state  ====>  NOUN
penitentary  ====>  NOUN
it  ====>  PRON
focuses  ====>  VERB
mainly  ====>  ADV
on  ====>  ADP
emerald  ====>  PROPN
city  ====>  PROPN
an  ====>  DET
experimental  ====>  ADJ
section  ====>  NOUN
of  ====>  ADP
the  ====>  DET
prison  ====>  NOUN
where  ====>  SCONJ
all  ====>  DET
the  ====>  DET
cells  ====>  NOUN
have  ====>  VERB
glass  ====>  NOUN
fronts  ====>  NOUN
and  ====>  CCONJ
face  ====>  VERB
inwards  ====>  NOUN
so  ====>  SCONJ
privacy  ====>  NOUN
is  ====>  AUX
not  ====>  PART
high  ====>  ADJ
on  ====>  ADP
the  ====>  DET
agenda  ====>  NOUN
em  ====>  PROPN
city  ====>  NOUN
is  ====>  AUX
home  ====>  NOUN
to  ====>  ADP
manyaryans  ====>  NOUN
muslims  ====>  PROPN
gangstas  ====>  PROPN
latinos  ====>  PROPN
christians  ====>  PROPN
italians  ====>  VERB
irish  ====>  ADJ
and  ====>  CCONJ
moreso  ====>  NOUN
scuffles  ====>  VERB
death  ====>  NOUN
stares  ====>  NOUN
dodgy  ====>  VERB
dealings  ====>  NOUN
and  ====>  CCONJ
shady  ====>  ADJ
agreements  ====>  NOUN
are  ====>  AUX
never  ====>  ADV
far  ====>  ADV
awayi  ====>  NOUN
would  ====>  AUX
say  ====>  VERB
the  ====>  DET
main  ====>  ADJ
appeal  ====>  NOUN
of  ====>  ADP
the  ====>  DET
show  ====>  NOUN
is  ====>  AUX
due  ====>  ADJ
to  ====>  ADP
the  ====>  DET
fact  ====>  NOUN
that  ====>  SCONJ
it  ====>  PRON
goes  ====>  VERB
where  ====>  SCONJ
other  ====>  ADJ
shows  ====>  NOUN
would  ====>  AUX
nt  ====>  PART
dare  ====>  VERB
forget  ====>  VERB
pretty  ====>  ADJ
pictures  ====>  NOUN
painted  ====>  VERB
for  ====>  ADP
mainstream  ====>  NOUN
audiences  ====>  NOUN
forget  ====>  VERB
charm  ====>  ADJ
forget  ====>  NOUN
romanceoz  ====>  NOUN
does  ====>  AUX
nt  ====>  PART
mess  ====>  VERB
around  ====>  ADP
the  ====>  DET
first  ====>  ADJ
episode  ====>  NOUN
i  ====>  PRON
ever  ====>  ADV
saw  ====>  VERB
struck  ====>  VERB
me  ====>  PRON
as  ====>  ADP
so  ====>  ADV
nasty  ====>  ADJ
it  ====>  PRON
was  ====>  AUX
surreal  ====>  ADJ
i  ====>  PRON
could  ====>  AUX
nt  ====>  PART
say  ====>  VERB
i  ====>  PRON
was  ====>  AUX
ready  ====>  ADJ
for  ====>  ADP
it  ====>  PRON
but  ====>  CCONJ
as  ====>  SCONJ
i  ====>  PRON
watched  ====>  VERB
more  ====>  ADV
i  ====>  PRON
developed  ====>  VERB
a  ====>  DET
taste  ====>  NOUN
for  ====>  ADP
oz  ====>  PROPN
and  ====>  CCONJ
got  ====>  VERB
accustomed  ====>  VERB
to  ====>  ADP
the  ====>  DET
high  ====>  ADJ
levels  ====>  NOUN
of  ====>  ADP
graphic  ====>  ADJ
violence  ====>  NOUN
not  ====>  PART
just  ====>  ADV
violence  ====>  NOUN
but  ====>  CCONJ
injustice  ====>  NOUN
crooked  ====>  VERB
guards  ====>  NOUN
who  ====>  PRON
ll  ====>  AUX
be  ====>  AUX
sold  ====>  VERB
out  ====>  ADP
for  ====>  ADP
a  ====>  DET
nickel  ====>  NOUN
inmates  ====>  NOUN
who  ====>  PRON
ll  ====>  AUX
kill  ====>  VERB
on  ====>  ADP
order  ====>  NOUN
and  ====>  CCONJ
get  ====>  VERB
away  ====>  ADP
with  ====>  ADP
it  ====>  PRON
well  ====>  ADV
mannered  ====>  ADJ
middle  ====>  ADJ
class  ====>  NOUN
inmates  ====>  VERB
being  ====>  AUX
turned  ====>  VERB
into  ====>  ADP
prison  ====>  NOUN
bitches  ====>  NOUN
due  ====>  ADJ
to  ====>  ADP
their  ====>  PRON
lack  ====>  NOUN
of  ====>  ADP
street  ====>  NOUN
skills  ====>  NOUN
or  ====>  CCONJ
prison  ====>  NOUN
experience  ====>  NOUN
watching  ====>  VERB
oz  ====>  ADP
you  ====>  PRON
may  ====>  AUX
become  ====>  VERB
comfortable  ====>  ADJ
with  ====>  ADP
what  ====>  PRON
is  ====>  AUX
uncomfortable  ====>  ADJ
viewingthats  ====>  NOUN
if  ====>  SCONJ
you  ====>  PRON
can  ====>  AUX
get  ====>  VERB
in  ====>  ADP
touch  ====>  NOUN
with  ====>  ADP
your  ====>  PRON
darker  ====>  ADJ
side  ====>  NOUN