**Text Representation**

In [4]:
#1. Bag of words
# we use countvectorisation

In [5]:
import numpy as np
import pandas as pd

In [6]:
df=pd.DataFrame({'text':['People watch cricket','player was player','people write comment'
,'cricket play comment'],'output':[1,1,0,0]})

In [7]:
df

                   text  output
0  People watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [8]:
#people watch cricket player was write comment play
#[11100000]
#[00021000]
#[10000110]
#[00100011]

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
cv=CountVectorizer()

In [11]:
bow=cv.fit_transform(df['text'])

In [12]:
#vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 6, 'cricket': 1, 'player': 4, 'was': 5, 'write': 7, 'comment': 0, 'play': 3}

In [13]:
print(bow[0].toarray())

[[0 1 1 0 0 0 1 0]]

In [15]:
cv.transform(['cricket watch and write comment of cricket comment']).toarray()

array([[2, 2, 0, 0, 0, 0, 1, 1]])

In [16]:
# 2. N-grams

In [17]:
v= CountVectorizer(ngram_range=(1,2))
#v=CountVectorizer(ngram_range=(2,2))

In [18]:
bow=v.fit_transform(df['text'])

In [19]:
df['text']

0    People watch cricket
1       player was player
2    people write comment
3    cricket play comment
Name: text, dtype: object

In [20]:
#vocab
print(v.vocabulary_)

{'people': 3, 'watch': 12, 'cricket': 1, 'people watch': 4, 'watch cricket': 13, 'player': 8, 'was': 10, 'player was': 9, 'was player': 11, 'write': 14, 'comment': 0, 'people write': 5, 'write comment': 15, 'play': 6, 'cricket play': 2, 'play comment': 7}

In [21]:
#TF(term Frequency)
# 2. IDF(Inverse Documnet Frequency)

In [22]:
#tf(t,d)=(Numer of occuracnces of term t in document d)/(Total number of term in the document d)

# example -->
# d1=people watch cricket.

# tf(people,d1)=1/3

# d2=match was match
# tf(match,d2)=2/3

In [23]:
#IDF(t) =Loge(Total number of document in the corpus)/(Number of documents with term t in them)

# here corpus means number of sentences

# Examples ==>
# d1 = people watch cricket
# d2=cricket was cricket
#d3=people write comment
# d4 =cricket write comment

#idf(cricket)=Log(4/4)
#idf(people)=Log(4/2)

In [24]:
# we can use this by applying feature_extraction method in sklearn

In [25]:
df

                   text  output
0  People watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.52640543, 0.52640543, 0.        , 0.        ,
        0.        , 0.66767854, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.89442719,
        0.4472136 , 0.        , 0.        ],
       [0.52640543, 0.        , 0.52640543, 0.        , 0.        ,
        0.        , 0.        , 0.66767854],
       [0.52640543, 0.52640543, 0.        , 0.66767854, 0.        ,
        0.        , 0.        , 0.        ]])

In [28]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073]
['comment' 'cricket' 'people' 'play' 'player' 'was' 'watch' 'write']

In [ ]:
#imdb-
# --> 20 rows
# --->cleaning
#tfidf